# Generated by Django 4.0.2 on 2022-03-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('price', models.CharField(max_length=20, verbose_name='Цена')),
                ('date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
